const ERROR_TOKENS = {
  CUSTOMER_NOT_ENABLED: 'CUSTOMER_IS_NOT_ENABLED',
  NO_LTI_TOKEN: 'NO_LTI_TOKEN',
  ERROR_IN_LTI_AUTH: 'ERROR_IN_LTI_AUTH',
  DEEP_LINKING_NOT_ENABLED: 'DEEP_LINKING_NOT_ENABLED',
  DYNAMIC_REGISTRATION_NOT_ENABLED: 'DYNAMIC_REGISTRATION_NOT_ENABLED',
};

export { ERROR_TOKENS };
